# Generated by Django 3.2.5 on 2021-11-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_hospital_id', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('contact_details', models.CharField(max_length=1000)),
                ('mail_id', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_supplier_id', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('location_of_supply_center', models.CharField(max_length=1000)),
                ('contact_details', models.CharField(max_length=1000)),
                ('mail_id', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalOxygenSupportedBedStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_oxygen_supported_beds', models.IntegerField(blank=True)),
                ('oxygen_supported_beds_incoming', models.IntegerField(blank=True)),
                ('oxygen_supported_beds_in_use', models.IntegerField(blank=True)),
                ('oxygen_supported_beds_taken_for_use', models.IntegerField(blank=True)),
                ('oxygen_supported_beds_free_for_use', models.IntegerField(blank=True)),
                ('oxygen_supported_beds_remaining', models.IntegerField(blank=True)),
                ('unique_hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osmsapp.hospitaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalOxygenCylinderStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_oxygen_cylinders_stock', models.IntegerField(blank=True)),
                ('incoming_oxygen_cylinders_stock', models.IntegerField(blank=True)),
                ('oxygen_cylinders_in_use', models.IntegerField(blank=True)),
                ('oxygen_cylinders_taken_for_use', models.IntegerField(blank=True)),
                ('oxygen_cylinders_remaining', models.IntegerField(blank=True)),
                ('unique_hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osmsapp.hospitaldetail')),
            ],
        ),
    ]
