# Generated by Django 3.2.5 on 2021-11-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='unique_hospital_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='unique_hospital_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
