# Generated by Django 3.2.5 on 2021-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmsapp', '0002_auto_20211110_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='oxygen_supported_beds_free_for_use',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='oxygen_supported_beds_in_use',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='oxygen_supported_beds_incoming',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='oxygen_supported_beds_remaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='oxygen_supported_beds_taken_for_use',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygensupportedbedstock',
            name='total_oxygen_supported_beds',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
