# Generated by Django 3.2.5 on 2021-11-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmsapp', '0003_auto_20211110_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='incoming_oxygen_cylinders_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='oxygen_cylinders_in_use',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='oxygen_cylinders_remaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='oxygen_cylinders_taken_for_use',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospitaloxygencylinderstock',
            name='total_oxygen_cylinders_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
