# Generated by Django 3.2.5 on 2021-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmsapp', '0004_auto_20211110_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaloxygencylinderstock',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaloxygensupportedbedstock',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
